# Generated by Django 4.2.5 on 2023-11-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('proveedor', models.ManyToManyField(related_name='proveedores', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Administradores',
            },
        ),
    ]
