# Generated by Django 4.2.5 on 2023-10-24 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('cuit', models.CharField(max_length=15, null=True, verbose_name='CUIT')),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateField(blank=True, verbose_name='Fecha de carga')),
                ('fecha_emision', models.DateField(blank=True, verbose_name='Fecha de emision')),
                ('tipo', models.CharField(choices=[('factura', 'FACTURA'), ('nota de credito', 'NOTA DE CRÉDITO'), ('nota de debito', 'NOTA DE DÉBITO'), ('proforma', 'PROFORMA')], verbose_name='Tipo de comprobante')),
                ('numero', models.CharField(max_length=13, verbose_name='Número de comprobante')),
                ('neto_gravado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Neto gravado')),
                ('neto_exento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Neto exento')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA')),
                ('retencion_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retencion de IVA')),
                ('retencion_iibb', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retención IIBB')),
                ('documento', models.FileField(null=True, upload_to='facturas/', verbose_name='Documento')),
                ('estado', models.IntegerField(default=0, verbose_name='Estado')),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
        ),
    ]
