# Generated by Django 4.2.5 on 2023-10-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateField(verbose_name='Fecha de carga')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emision')),
                ('tipo', models.CharField(verbose_name='Tipo de comprobante')),
                ('numero', models.CharField(verbose_name='Numero de comprobante')),
                ('neto_gravado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Importe neto gravado')),
                ('neto_exento', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Importe neto exento')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='IVA')),
                ('retencion_iva', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Retenciones IVA')),
                ('retencion_iibb', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Retenciones IIBB')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('documento', models.FileField(upload_to='documentos/facturas/', verbose_name='Documento')),
            ],
        ),
    ]
