# Generated by Django 4.2.6 on 2023-10-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='documento',
            field=models.FileField(upload_to='comprobantes/', verbose_name='Documento'),
        ),
    ]
